import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Board } from '../components/board'
import { useBoard, useFetch } from '../hooks'
import { useState } from 'react'
import { difficulties, randomDifficulty } from '../common/util/difficulty'

export default function Home() {
  const {
    board,
    set,
    update,
    clear,
    validate,
    solve,
    loadNewBoard,
    difficulty,
    setDifficulty,
  } = useBoard(difficulty)
  const [valid, setValid] = useState(true)

  return (
    <div className={styles.container}>
      <Head>
        <title>Sudoku</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Board board={board} updateCell={update} />
        <button
          onClick={() => {
            solve()
          }}
        >
          Solve
        </button>
        <button
          onClick={() => {
            setValid(validate())
          }}
        >
          Validate
        </button>
        <div>{valid ? 'valid' : 'invalid'}</div>
        <button
          onClick={() => {
            difficulty !== difficulties.easy
              ? setDifficulty(difficulties.easy)
              : loadNewBoard()
          }}
        >
          Easy
        </button>
        <button
          onClick={() => {
            difficulty !== difficulties.medium
              ? setDifficulty(difficulties.medium)
              : loadNewBoard()
          }}
        >
          Medium
        </button>
        <button
          onClick={() => {
            difficulty !== difficulties.hard
              ? setDifficulty(difficulties.hard)
              : loadNewBoard()
          }}
        >
          Hard
        </button>
        <button
          onClick={() => {
            const newDifficulty = randomDifficulty()
            difficulty !== newDifficulty
              ? setDifficulty(newDifficulty)
              : loadNewBoard()
          }}
        >
          Random
        </button>
        <div>{difficulty}</div>
        <button
          onClick={() => {
            clear()
          }}
        >
          Clear
        </button>
      </main>
    </div>
  )
}
