import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Icon from '../public/ksudoku.ico'
import { Board } from '../components/board'
import { useBoard } from '../hooks'
import { useState } from 'react'
import { difficulties, randomDifficulty } from '../common/util/difficulty'
import { Button } from '../components/common'

export default function Home() {
  const { board, update, clear, validate, solve, difficulty, setDifficulty } =
    useBoard()
  const [valid, setValid] = useState(true)

  return (
    <div className={styles.container}>
      <Head>
        <title>Sudoku</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/ksudoku.ico' />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <h1>Sudoku</h1>
          <Image src={Icon} alt='Sudoku Icon' width={75} height={75} />
        </div>
        <Board board={board} updateCell={update} />
        <div className={styles.buttonBar}>
          <h2>Difficulty:</h2>
          <Button
            onClick={() => {
              setDifficulty(difficulties.easy)
            }}
            selectable
            selected={difficulty === difficulties.easy}
          >
            Easy
          </Button>
          <Button
            onClick={() => {
              setDifficulty(difficulties.medium)
            }}
            selectable
            selected={difficulty === difficulties.medium}
          >
            Medium
          </Button>
          <Button
            onClick={() => {
              setDifficulty(difficulties.hard)
            }}
            selectable
            selected={difficulty === difficulties.hard}
          >
            Hard
          </Button>
          <Button
            onClick={() => {
              setDifficulty(randomDifficulty())
            }}
            selectable
          >
            Random
          </Button>
          <Button
            onClick={() => {
              clear()
            }}
            selectable
          >
            Clear
          </Button>
        </div>
        <div>
          <Button
            onClick={() => {
              setValid(validate())
            }}
          >
            Validate
          </Button>
          <div>{valid ? 'valid' : 'invalid'}</div>
        </div>
        <Button
          onClick={() => {
            solve()
          }}
        >
          Solve
        </Button>
      </main>
    </div>
  )
}
