import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Board } from '../components/board'
import { useBoard } from '../hooks'
import { useState } from 'react'
import { difficulties, randomDifficulty } from '../common/util/difficulty'

export default function Home() {
  const { board, update, clear, validate, solve, difficulty, setDifficulty } =
    useBoard()
  const [valid, setValid] = useState(true)

  return (
    <div className={styles.container}>
      <Head>
        <title>Sudoku</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Board board={board} updateCell={update} />
        <button
          onClick={() => {
            solve()
          }}
        >
          Solve
        </button>
        <button
          onClick={() => {
            setValid(validate())
          }}
        >
          Validate
        </button>
        <div>{valid ? 'valid' : 'invalid'}</div>
        <button
          onClick={() => {
            setDifficulty(difficulties.easy)
          }}
        >
          Easy
        </button>
        <button
          onClick={() => {
            setDifficulty(difficulties.medium)
          }}
        >
          Medium
        </button>
        <button
          onClick={() => {
            setDifficulty(difficulties.hard)
          }}
        >
          Hard
        </button>
        <button
          onClick={() => {
            setDifficulty(randomDifficulty())
          }}
        >
          Random
        </button>
        <div>{difficulty}</div>
        <button
          onClick={() => {
            clear()
          }}
        >
          Clear
        </button>
      </main>
    </div>
  )
}
